# ----------------------------------------------------------------------
#
# FILE: Ldmx.ini
#
# DESCRIPTION
# -----------
# The Ldmx.ini file contains the values for all the one-time settings.
# This file is only read upon the relevant executables start-up.
# Contrast this with the Ldmx.conf file.  This file is reread at the
# start of every run thus providing run specific parameters.
#
# Currently only the Log Collector and the Data Producers have such
# parameters.
#
# ----------------------------------------------------------------------
[LogCollector.log]
EULOG_GUI_LOG_FILE_PATTERN = /tmp/jj/ldmx/log/ldmx_$12D.log


[Producer.Ldmx0]
LDMX_DEV_LOCK_PATH             = /tmp/jj/ldmx/management/LdmxDev0.lock
LDMX_CONFIGURATION             = /u/ey/russell/Experiments/ldmx/daq/misc/emulator/LdmxTest.cfg;
LDMX_CONNECTION_TIMEOUT        = 8
LDMX_NFRAGMENTS                = 11

LDMX_SOURCES                   = localhost:8190,localhost:8191

LDMX_TRIGGER_PIPE              = /tmp/ldmxTriggerPipe
LDMX_NTRIGGER_BATCHES          = 9
LDMX_NTRIGGER_EVENTS_PER_BATCH = 64

LDMX_NSVT_BATCHES              = 10
LDMX_NSVT_EVENTS_PER_BATCH     = 32

LDMX_NRSSI_FRAMES               = 32

[Producer.Ldmx1]
LDMX_DEV_LOCK_PATH = /tmp/jj/ldmx/management/LdmxDev1.lock
