# ----------------------------------------------------------------------
#
# FILE: Ldmx.conf
#
# DESCRIPTION
# -----------
# The Ldmx.conf contains run specific parameters. Since this file is
# reread upon the start of every run, the parameters can be changed at
# the start of every run.  Contrast the configuration file (.conf)
# with the initialization file (.ini), which is read and parsed once at
# the start of the revelant executable.
#
# NOTE
# ----
# The section names are formatted as
#
#    <Type>.<InstanceName>   Example: Producer.Ldmx0
#
# The Type is one from the fixed set of
#     { RunControl, LogCollector, Producer, DataCollector, Monitor }
#
# Exceptions to the rule:
#   1. RunControl    -- there is only one, so it has no instance name
#   2. LogCollector  -- the instance name is fixed as "log"
#
# ----------------------------------------------------------------------


[RunControl]
# ----------
LDMX_STOP_RUN_AFTER_N_SECONDS  = 60
config_log_path                = /tmp/jj/ldmx/conf/

# from the base RunControl.cc
EUDAQ_CTRL_PRODUCER_LAST_START = Ldmx0
EUDAQ_CTRL_PRODUCER_FIRST_STOP = Ldmx1

# Steer which values to display in the GUI:
# producerName and displayed value are seperated by a ",". 
# ADDITIONAL_DISPLAY_NUMBERS = "log,_SERVER"



[Producer.Ldmx0]
# ---------------
# Connection to the data collector
EUDAQ_DC = LdmxDc

# Config-parameters of the example producer
LDMX_PLANE_ID             = 0
LDMX_DURATION_BUSY_MS     = 100
LDMX_ENABLE_TIMESTAMP     = 0 
LDMX_ENABLE_TRIGGERNUMBER = 1


[Producer.Ldmx1]
# ---------------
# Connection to the data collector
EUDAQ_DC = LdmxDc

# Config-parameters of the example producer
LDMX_PLANE_ID             = 1
LDMX_DURATION_BUSY_MS     = 1000
LDMX_ENABLE_TRIGGERNUMBER = 1
LDMX_ENABLE_TIMESTAMP     = 0 


[DataCollector.LdmxDc]
# ---------------------
# connection to the monitor
EUDAQ_MN                            = LdmxMon
EUDAQ_FW                            = native
EUDAQ_FW_PATTERN                    = /tmp/jj/ldmx/data/run$3R_$12D$X
EUDAQ_DATACOL_SEND_MONITOR_FRACTION = 10


# Config-parameters of the example data collector
LDMX_DISABLE_PRINT                   = 0


[Monitor.LdmxMon]
# Undocumented, but sets the monitoring fraction
# EUDAQ_DATACOL_SEND_MONITOR_FRACTION = 10

LDMX_ENABLE_PRINT         = 0
LDMX_ENABLE_STD_PRINT     = 0
LDMX_ENABLE_STD_CONVERTER = 1

